### ISSUE TITLE
// TODO:

### ISSUE THREAD

**Issue by LeoRiether** [LeoRiether/Oberon-Scala#1]
- [ ] Implementar visitVariable: @rafaelcn 
- [ ] Implementar visitFunctionCall: @MarcusABR 
- [ ] Arrumar o Environment: @rafaelnogalha , @gustavo-tomas 
- [ ] ModuleLoader.getContent e .findModulePath: @LeoRiether 
- [ ] Testes do interpretador (TDD?): @andrelarrosacrypt
